repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-add-large-files
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.9b0  
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1  
    hooks:
    - id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  
    hooks:
    - id: flake8
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.1  
    hooks:
    - id: mdformat
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  
    hooks:
    - id: mypy
      files: ^src/
      args: []
-   repo: https://github.com/pytest-dev/pytest
    rev: v7.0.1  
    hooks:
    - id: pytest
